### ISSUE TITLE
Why are my .JS files huge?

### ISSUE THREAD

**Issue by darkvodka** [devias-io/material-kit-react#101]
Hello,

I have downloaded the latest version of "Free React Admin Dashboard".
When I run it on my PC in dev mode or build the production version (without changing the code), I find myself with a chunk.js file of more than 1Mb. This is obviously problematic because the page is long to load.

![me](https://user-images.githubusercontent.com/59097333/129438655-f4798183-a1e2-4f34-8ca7-4060440d180a.png)

But if I go on the demo page https://material-kit-react.devias.io/app/dashboard there are no big .js files

![demo](https://user-images.githubusercontent.com/59097333/129438659-f15fb312-9646-4dd1-aec3-a61b325e28a8.png)

How is it possible ?

**Comment by arobert93** [comment]
Do you build your production files with source maps?
