### ISSUE TITLE
React-router breaking changes v6.0.0-beta.4

### ISSUE THREAD

**Issue by simonsent** [devias-io/material-kit-react#102]
Hello,

React router version v6.0.0-beta.4 release removes the ability for nested route paths to begin with "/". (1)

The Pro package will need to be updated by simply remving "/" or the path from a children route index altogether.

(1) https://github.com/remix-run/react-router/releases/tag/v6.0.0-beta.4

**Comment by arobert93** [comment]
Thank you for submitting the solution!
