### ISSUE TITLE
missing sidebar on hd screen

### ISSUE THREAD

**Issue by binotby** [devias-io/material-kit-react#105]
![image](https://user-images.githubusercontent.com/32414473/133378308-0f929f84-fc29-4e98-8b9b-4c90c00fcbe2.png)

**Comment by Nalindadsn** [comment]
yes its not working

**Comment by AppElent** [comment]
Bump!

**Comment by Dhruv1993** [comment]
if you increase the width above 1550 it works

**Comment by Dhruv1993** [comment]
Under components > DashboardSidebar.js > line 181
change the Hidden component, change it to mdDown, it will work for the desktops but play around with breakpoints to fine tune the xs,xl or md etc

**Comment by Dhruv1993** [comment]
Change line 33 to 
`{ path: '/', element: <Navigate to="/login" /> },`

Default route will now point to login when running localhost:3000

**Comment by navegeri** [comment]
The problem is with the xlUp and lgDown in the hidden components in DashboardNavbar and DashboardSidebar.

**Comment by arobert93** [comment]
We updated the design and this includes a fix for the sidebar.

**Comment by navegeri** [comment]
👍
