### ISSUE TITLE
Refreshing page when using auth0 causes logout.

### ISSUE THREAD

**Issue by Cmdv** [devias-io/material-kit-react#109]
Hi lovely kit,

I've found an odd bug where when activating the auth0 popup login (paid version), everything works fine but if I refreshed when inside the an authenticated page `/dashboard/x` it just logs me out 😢 

Any pointers would be greatly appreciated as this makes it rather unusable. When testing the demo where it uses JWT everything seems to work correctly.

**Comment by arobert93** [comment]
Closing this since this is a PRO related issue.
