### ISSUE TITLE
The navbar toggle button doesn't work

### ISSUE THREAD

**Issue by znadir** [devias-io/material-kit-react#139]
Reproduction steps:

1. Open the live example
2. Resize the browser window to make it the same as mobile resolution.
3. Click on the button to display the navbar.

Expected behavior:

- The navbar should be displayed when the button is clicked

Actual behavior:

- The navbar toggle button doesn't work

**Comment by ralphdelara** [comment]
Hi @nadirzebiri 
I fixed it in my local by setting default openNav state to false

> setting its default to false to avoid seeing nav on page load on < 1200 screens

then updating useEffect to
```
useEffect(() => {
    if (screen.width > 1199) {
      setOpenNav(true);
    }
 }, []);
```

>  screen.width > 1199 means it will show the nav on page load on >= 1200 screens

 Hope this helps :)

**Comment by znadir** [comment]
Thanks for the solution. However, i think using `window.innerWidth` is better approach than `screen.width`. I'll keep this issue open until it's resolved in the repository.

**Comment by acomanescu** [comment]
Thank you @nadirzebiri @ralphdelara, the issue was the useEffect implementation. It should work as expected now.
