### ISSUE TITLE
Link to Figma file broken

### ISSUE THREAD

**Issue by GuidovTricht** [devias-io/material-kit-react#149]
Hi,

I'd like to access the Figma file referenced in the README, but the link is broken and refers to a 404.
Could somebody provide a new link?

Thanks in advance!

**Comment by adrianmanea** [comment]
Hey! Could you please send a screenshot of the link's location in the README? I'm having trouble finding it.

**Comment by GuidovTricht** [comment]
Hi @adrianmanea,

I'm referring to the Free Figma Community File link:
![image](https://github.com/devias-io/material-kit-react/assets/1440052/d34adde7-db1b-4937-b8bc-653f10a50ffc)
When I open it, I get to see a 404. Perhaps it's not public anymore?

**Comment by adrianmanea** [comment]
Figma seems to have remove it from the community, here's a duplicate: https://www.figma.com/file/b3L1Np4RYiicZAOMopHNkm/Devias-Dashboard-Design-Library-Kit?type=design&node-id=0%3A1&mode=design&t=EUlYNGKjT84fT3lA-1

**Comment by GuidovTricht** [comment]
I got a copy of it now, thank you so much!
