### ISSUE TITLE
Devias Dashboard Design Library Kit broken Link

### ISSUE THREAD

**Issue by marksikaundi** [devias-io/material-kit-react#155]
Could you fix this 404 error for the Figma link -> https://www.figma.com/community/file/1039837897183395483/Devias-Dashboard-Design-Library-Kit It is the one in the readme file?

**Comment by adrianmanea** [comment]
Hi, here's the file which can be duplicated: https://www.figma.com/file/b3L1Np4RYiicZAOMopHNkm/Devias-Dashboard-Design-Library-Kit?type=design&node-id=0%3A1&mode=design&t=EUlYNGKjT84fT3lA-1

**Comment by marksikaundi** [comment]
> Hi, here's the file which can be duplicated: https://www.figma.com/file/b3L1Np4RYiicZAOMopHNkm/Devias-Dashboard-Design-Library-Kit?type=design&node-id=0%3A1&mode=design&t=EUlYNGKjT84fT3lA-1

Thanks and Maybe consider updating the repo with this link as per the old one doesn't work.

**Comment by acomanescu** [comment]
Updated
