### ISSUE TITLE
Free Figma Comunity File Not Found (404)

### ISSUE THREAD

**Issue by Spike433** [devias-io/material-kit-react#157]
[Link](https://www.figma.com/community/file/1039837897183395483/Devias-Dashboard-Design-Library-Kit) not found in [**Free Figma Community File**](https://github.com/devias-io/material-kit-react#free-figma-community-file) section.

**Comment by adrianmanea** [comment]
We need to update the link, apologise, here's the new one: https://github.com/devias-io/material-kit-react/issues/155#issuecomment-1827813279

**Comment by acomanescu** [comment]
Updated
