### ISSUE TITLE
project is not running with nextJS 14.0.4

### ISSUE THREAD

**Issue by varsha22** [devias-io/material-kit-react#160]

**Comment by nullcryptodev** [comment]
I'm also using Next.js 14.0.4 and haven't ran into an issue regarding this not working.

Steps I took:
1) Cloned repo
2) `npm install`
3) `npm audit --fix`
4) `npm run dev`

![image](https://github.com/devias-io/material-kit-react/assets/155117721/152fc95b-e290-4226-bea8-cbbc00860e24)

**Comment by acomanescu** [comment]
@varsha22 It would be nice to have some logs.

**Comment by hafizhuseynov** [comment]
I temporarily downgraded the nextjs version to 13.1.6, it works for now
npm install next@13.1.6

**Comment by acomanescu** [comment]
I've updated the project to use Next.js App Router.
