### ISSUE TITLE
Property 'signUp' does not exist on type 'AuthClient'. Did you mean 'SignUp'?

### ISSUE THREAD

**Issue by elmoisedecuba** [devias-io/material-kit-react#165]
https://github.com/devias-io/material-kit-react/blob/b0a6bfbeaa641261d8d49294386653bba37d2ef7/src/components/auth/sign-up-form.tsx#L55

**Comment by acomanescu** [comment]
The method is exposed by the client is `signUp` (camelCase). Not sure why you got that error.

**Comment by acomanescu** [comment]
Closing this issue. If it persists, please reopen.
