### ISSUE TITLE
Add `exact` property for NavItem in NavBar

### ISSUE THREAD

**Issue by duyphanz** [devias-io/material-kit-react#56]
I got an issue in case I have defined 2 routes as `/` and `/product` and when the `/product` route is active, both items in NavBar are active as well.

I'd suggest that we add one more `exact` property for `RouterLink` to avoid this problem for someone who is not familiar with `react-router-dom` don't get confused in this case.

```
<Button
    exact // new added
    activeClassName={classes.active}
    className={classes.button}
    component={RouterLink}
    to={href}
>
```

ref: https://github.com/devias-io/react-material-dashboard/blob/3e74c66f509afb99acd5960ed9a217e34fd99b2d/src/layouts/DashboardLayout/NavBar/NavItem.js#L58

**Comment by alexrobaina** [comment]
Hi @duyphanz, I can help with this issue! Do you think it's ok?

**Comment by duyphanz** [comment]
> Hi @duyphanz, I can help with this issue! Do you think it's ok?

I don't know if the repository's owner does agree with this issue or not. If yes, then it's okay, feel free to make your PR @alexrobaina
