### ISSUE TITLE
Support of virtual list

### ISSUE THREAD

**Issue by imosapatryk** [devias-io/material-kit-react#57]
Hi,

does your normal or pro kit support virtual lists?

**Comment by arobert93** [comment]
Hi @imosapatryk,

Unfortunately at the moment we do not have virtual lists, but it could be an interesting idea for our next update. Meanwhile we recommend using one these solutions: [react-window](https://github.com/bvaughn/react-window), [react-virtualized](https://github.com/bvaughn/react-virtualized) or [react-virtuoso](https://github.com/petyosi/react-virtuoso).
