### ISSUE TITLE
Table pagination not working

### ISSUE THREAD

**Issue by fazlan-nazeem** [devias-io/material-kit-react#63]
Table pagination does not seem to work properly when we click on the next page button(in default mode can be reproduced when items per page are set to 5). 

This is in customer page.

**Comment by arobert93** [comment]
Hi @fazlan-nazeem,

We did not add that functionality, but here is a quick solution.

```js
const applyPagination = (customers, page, limit) => {
  return customers.slice(page * limit, page * limit + limit);
};
```

This function allows you to paginate your customers depending on page size and page number. Now replace this part

```js
{customers.slice(0, limit).map((customer) => (
```

With

```js
{applyPagination(customers, limit, page).map((customer) => (
```

We'll add it in our next update.
