### ISSUE TITLE
Figma / Sketch download is not working

### ISSUE THREAD

**Issue by rafi73** [devias-io/material-kit-react#67]
Hi,

Thank you so much for this template. I've tried to download the figma/sketch but it's failing.

**Comment by KarthikeyanSJ** [comment]
@rafi73 That is for Paid Version Only

**Comment by oliviertassinari** [comment]
It might make sense to clarify it. The links in https://github.com/devias-io/material-kit-react#-design-files could be confusing.

**Comment by arobert93** [comment]
@rafi73, we expect to have them available this weekend. Please note that they are using an old version and they do not represent the PRO design files.

**Comment by adrianmanea** [comment]
Figma added as a community file.
