### ISSUE TITLE
Table body is not scrolled vertically in mobile design

### ISSUE THREAD

**Issue by baymax1234** [devias-io/material-kit-react#68]
The table is not scrolled vertically when switching to mobile. Sometimes it's available, but in the console, there are a lot of errors.

touch.js:169 [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

It would be great if there is a solution.

**Comment by Mai9550** [comment]
do you mean 'horizontally' because it already scrolls vertically

**Comment by baymax1234** [comment]
Yes, and vice versa.
If it's already scrolled horizontally, it shouldn't scroll vertically.

**Comment by Mai9550** [comment]
Can you please refer to me the place of the 'last orders' table component ?as it's taking long to find it

**Comment by Mai9550** [comment]
the scrollbar appears when you click the table, is this not desirable?

**Comment by baymax1234** [comment]
It's fixed now. Thanks.

**Comment by Mai9550** [comment]
No problem
