### ISSUE TITLE
Expected LF but found CRLF on W10 VSCode

### ISSUE THREAD

**Issue by Mingyang-Li** [devias-io/material-kit-react#87]
I downloaded the template and created a few new components by copy-pasting some existing components and tweaked the text only. When I started the app, it crashed and gave me this error
`Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style`

My question is, Was your template written on Linux? If so, what are the best ways to make the template work on W10 code editors? Or what could be the linebreak settings I can do on my end to keep my code running?

**Comment by Mingyang-Li** [comment]
Btw, the number of lines I got that error message is the same as the number of lines of code I copy-pasted from one of the components. My guess here would be that W10 copy-pasting supports CRLF only but not LF, which is presumably what the original template setup to use. Not 100% sure though, what are your thoughts?

**Comment by arobert93** [comment]
Hi @Mingyang-Li, I've added the `.gitattributes` file with LF set up by default. Could you, please, clone it again and check if the CRLF warning persists?

**Comment by Mingyang-Li** [comment]
Hi @arobert93, I've cloned `.gitattributes` file into the root directory of my project folder, the warnings still persists.

**Comment by arobert93** [comment]
@Mingyang-Li you have to clone the entire repo again because you already have the files cloned with CRLF. It's a git configuration.

You have two options, set git config globally or locally (per repo). Once you clone the files, they use the already defined EOL, which in your case is CRLF.

**Comment by Mingyang-Li** [comment]
I've cloned the entire repo onto VSCode again, it works fine when I don'
t edit anything (just like before I opened this issue), but crashes every time I add new components and put then onto the Dashboard.js page. 

I've also tried `git config --global core.autocrlf true` command on my project root folder terminal, still haven't solved this issue...

**Comment by Mingyang-Li** [comment]
No worries, I found a way around it. 

Since I haven't written too much code, I was just coding the new files within the new repo and turned off the 'Format on Paste' checkbox from VSCode settings => Text Editor.

**Comment by Mingyang-Li** [comment]
All I wanted to do with this template was freely copy-paste and tweak components from one file to another because this makes development much faster. **However, every single time I copy-paste, I get 'expect LF' but got 'CRLF' error.** I'm still unsure what's wrong here, almost going furious... Help pls --- what's something within the configuration that's forcing LF but not CRLF?

[
![image](https://user-images.githubusercontent.com/53138432/115874401-2b196180-a498-11eb-902a-7584e75e979e.png)
](url)
[
![image](https://user-images.githubusercontent.com/53138432/115874479-408e8b80-a498-11eb-9b69-6d0d8462ea1a.png)
](url)

**Comment by valipopescu** [comment]
When copying snippets in windows, the operating system puts a CRLF in your clipboard automatically to replace the original LF.

I think your `.editorconfig` file does not have a LF setting for your editor

Should this be the case, you can fix this in the following ways:

- In your VSCode you need to set the end of line setting to \n (LF) instead of the windows default which is CRLF. 

- through `.editorconfig` file If you want to make this setting stay in all your projects, please edit your `.editorconfig` file and add the following at the beginning of the file:
```
[*]
end_of_line = lf
```

Theoretically, this should ... most likely solve your issue.
Usually programmers use LF as it covers every operating system unlike the windows specific LF, or the old macos specific  (before Mountain Lion) CR (\r)

**Comment by rocksnow1942** [comment]
> All I wanted to do with this template was freely copy-paste and tweak components from one file to another because this makes development much faster. **However, every single time I copy-paste, I get 'expect LF' but got 'CRLF' error.** I'm still unsure what's wrong here, almost going furious... Help pls --- what's something within the configuration that's forcing LF but not CRLF?
> 
> [ ![image](https://user-images.githubusercontent.com/53138432/115874401-2b196180-a498-11eb-902a-7584e75e979e.png) ](url)
> [ ![image](https://user-images.githubusercontent.com/53138432/115874479-408e8b80-a498-11eb-9b69-6d0d8462ea1a.png) ](url)

I had the same problem,  I solved this by adding: 

`"linebreak-style": 0`

to `.eslintrc` under "rules".

**Comment by Mingyang-Li** [comment]
Thanks a lot! @valipopescu @rocksnow1942
