### ISSUE TITLE
Hidden component

### ISSUE THREAD

**Issue by brunoguedao** [devias-io/material-kit-react#90]
The Hidden component is out of material ui 5 version

./src/components/DashboardSidebar.js
Attempted import error: 'Hidden' is not exported from '@material-ui/core'.

**Comment by valipopescu** [comment]
Please re install using npm rather than using other package managers and re-test.
In regards to changes in the upstream of the packages, we will update the package-lock.json once those packages are supported.

**Comment by philippbruhin** [comment]
It looks like in `@material-ui/core": "5.0.0-alpha.28"` import `Hidden` is still possible, wheras it is not in  `"@material-ui/core": "5.0.0-alpha.33"`.

For me it worked as described [here](https://github.com/mui-org/material-ui/issues/19704#issuecomment-612034247).

### Do not show on large and up
```
<Hidden lgUp>
  some additional code here
</Hidden>
```
Solution without `Hidden` component:
```
<Box display={{ lg: 'none' }}>
  some additional code here
</Box>
```

### Do not show below large
```
<Hidden lgDown>
  some additional code here
</Hidden>
```
Solution without `Hidden` component:
```
<Box display={{ xs: 'none', lg: 'block' }}>
  some additional code here
</Box>
```

**Comment by BenjaminFJohns** [comment]
> It looks like in `@material-ui/core": "5.0.0-alpha.28"` import `Hidden` is still possible, wheras it is not in `"@material-ui/core": "5.0.0-alpha.33"`.
> 
> For me it worked as described [here](https://github.com/mui-org/material-ui/issues/19704#issuecomment-612034247).
> 
> ### Do not show on large and up
> ```
> <Hidden lgUp>
>   some additional code here
> </Hidden>
> ```
> 
> Solution without `Hidden` component:
> 
> ```
> <Box display={{ lg: 'none' }}>
>   some additional code here
> </Box>
> ```
> 
> ### Do not show below large
> ```
> <Hidden lgDown>
>   some additional code here
> </Hidden>
> ```
> 
> Solution without `Hidden` component:
> 
> ```
> <Box display={{ xs: 'none', lg: 'block' }}>
>   some additional code here
> </Box>
> ```

This worked great for me running 5.0.0-alpha.34

**Comment by cunneen** [comment]
#93 seems to address this.
