### ISSUE TITLE
Error: useRoutes() may be used only in the context of a <Router> component

### ISSUE THREAD

**Issue by ngamanning** [devias-io/material-kit-react#91]
App.js throw _Error: useRoutes() may be used only in the context of a <Router> component_

This does not work: 
```
const App = () => {
  const routing = useRoutes(routes);
  return (
    <ThemeProvider theme={theme}>
      <GlobalStyles />
      {routing}
    </ThemeProvider>
  );
};
```

It looks like we need to wrap app inside Router like so:
```
const AppRoute = () => {
    const routing = useRoutes(routes);
    return (
        <ThemeProvider theme={theme}>
            <GlobalStyles />
            {routing}0
        </ThemeProvider>
    );
}
const App = () => {
    return (
        <Router>
            <AppRoute />
        </Router>
    );
};

```

**Comment by Pasitto** [comment]
Please try to add <Router> in index not inside <App>
```
import React from 'react';
import ReactDOM from 'react-dom';
import {BrowserRouter as Router} from 'react-router-dom';

import App from './App';

const element = (
  <Router>
    <App />
  </Router>
);

const container = document.getElementById('root');
ReactDOM.render(element, container);
```

That's work for me
Ref. : https://typescript.tv/react/upgrade-to-react-router-v6/

**Comment by adamnowocin** [comment]
check if you got version 6.2.1 in your package.json and if so update it to 6.2.2:

```
"react-router": "6.2.2",
"react-router-dom": "6.2.2",
```

**Comment by sourcecode71** [comment]
You should have a <BrowserRouter> (or any of [the provided routers](https://github.com/remix-run/react-router/blob/main/docs/api.md)) higher up in the tree. The reason for this is that the <BrowserRouter> provides a history context which is needed at the time the routes are created using useRoutes(). Note that higher up means that it can't be in the <App> itself, but at least in the component that renders it.

Here's what your entry point could look like:

import ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';


ReactDOM.render(
  <BrowserRouter>
    <App />
  </BrowserRouter>,
  document.getElementById('root'),
);
