### ISSUE TITLE
bar chart triggers several deprecated warnings

### ISSUE THREAD

**Issue by lukelu0520** [devias-io/material-kit-react#95]
Dear material-kit-react friends,

bar chart has several deprecated usages as shown in attached screenshot, including Axes.barPercentage, barThcknes, etc. 

We are using Ubuntu 18.04, Chrome Version 90.0.4430.93 (Official Build) (64-bit).
Hope to hear your expertise to fix these warnings.

Best,
--Luke

![Screenshot from 2021-06-10 12-40-26](https://user-images.githubusercontent.com/36803293/121587311-7efced00-c9e9-11eb-8560-f944ae3260da.png)

**Comment by arobert93** [comment]
With the latest update, these warnings are now fixed.
