### ISSUE TITLE
App loads to dashboard page and not login

### ISSUE THREAD

**Issue by clintg6** [devias-io/material-kit-react#97]
Whenever I load the app, it automatically redirects to /app/dashboard. I tried updating route.js under path: 'app' to use element <Login /> which gave me a login screen but when you click sign in it just goes gray and doesn't redirect to the dashboard. 

How can I get it to load the login page first when going to localhost:3000 then after clicking sign in it loads the dashboard? 

Thanks

**Comment by lukelu0520** [comment]
Got the the issue, hope to hear more expertise to implement login. Best, --Luke

**Comment by arobert93** [comment]
There can be a different strategy implemented. You put a wrapper over the dashboard pages as element, that checks if the user needs login or not. If true, you redirect to login route, otherwise you render the wrapper's children.

**Comment by francisJun** [comment]
You can do something like this.  
in routes.js

![routes](https://user-images.githubusercontent.com/43418025/133002788-39787fe5-9cb3-4fc4-896a-54e95d522817.PNG)

and in the ProtectedRoute component I have this code.

![protected](https://user-images.githubusercontent.com/43418025/133002922-e0c00f52-1390-4fe2-b347-20058d9f5bc8.PNG)


I hope this helps.
