### ISSUE TITLE
window.scrollTo(0,0) doesn't work with Dashboard Layout components

### ISSUE THREAD

**Issue by lukelu0520** [devias-io/material-kit-react#98]
Dear material-kit-react friends, 

window.scrollTo(0,0) stops working when I am using the dashboard template.
window.scrollTo(0,0) is the recommended way for react-router to navigate back to the top when a page changes.

Because of this issue it is hard for users to navigate around the website (for example if you scroll down and then hit a link, you enter the next page at the bottom).

Does anyone find a good solution ? Hope to hear your expertise.

--Luke

**Comment by arobert93** [comment]
Hi @lukelu0520, with the latest update, we migrated to Next.js and this no longer represents an issue since it handles the  auto scroll reset on page change.
